[package]
name = "nike-runtime"
version = "0.1.0"
edition = "2024"

[dependencies]
color-eyre.workspace = true
tokio.workspace = true
tokio-tungstenite.workspace = true
tracing = { workspace = true, features = ["async-await"] }
tracing-subscriber = { version = "0.3.19", features = ["env-filter"] }
nike-database = { path = "../database" }
nike-socket = { path = "../socket" }
metrics-exporter-prometheus = "0.18.3"
